apiVersion: v1
kind: Service
metadata:
  name: api-profiles
  labels:
    app: api-profiles
spec:
  type: ClusterIP
  clusterIP: "None"
  selector:
    app: api-profiles
  sessionAffinity: None
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
